---
##kcl hand config parameters 

##motor direction 
motor_direction: [1, -1, -1, -1, 1]

joint_sensor_calibration:
  palm_sensor1: 781.0
  palm_sensor2: 775.0
  finger_sensor3: 533.0
  finger_sensor4: 502.0
  finger_sensor5: 499.0

left_finger_sensor_direction: 1